### PR TITLE
feat: move to file action

### PR DESCRIPTION
**Pull request by yioneko**
https://github.com/yioneko/nvim-vtsls/assets/65551246/9b64c7aa-5e6c-4cf7-a48d-cd18d7e477b0

### CODE REVIEW

**Comment by yioneko** [comment]
@unphased Could you try this branch with vtsls on HEAD?

**Comment by unphased** [comment]
alright so i will switch to pnpm as that seems likely what i need to succeed

**Comment by yioneko** [comment]
I've put `shallow = true` in [`.gitmodules`](https://github.com/yioneko/vtsls/blob/66add9918f7511612c214c3ab354d090e61469fa/.gitmodules#L4), I think it is shallow clone by default (the code base is still large though).

**Comment by unphased** [comment]
i found that `packages/server/bin/vtsls.js` is where i can launch the server from, after i get pnpm to build it. But since package.json was missing further hints I still don't know how to install it. 

I found also that vtsls miraculously showed up on my linux environment installed by Mason. Indeed mason can auto install vtsls. I am beginning to feel that configuring Mason to target HEAD commit of vtsls should be my path forward. Sorry for the delay.

**Comment by unphased** [comment]
OK i learned more things 
- changes on vstls side are in the service dir
- couldnt get it working, so far i have vstls installable via mason so trying to test from there. So, have now also confirmed the code fetched by mason is not the latest, by confirming presence of `var UNSUPPORTED_ACTIONS = ["refactor.move.file"];`. Noted mason's vtsls install has the js code in a bundle.

I think I will be golden if i can just work out how to tell mason to grab main instead of specific commit. 
I would also be golden if i could get: 

- build/deploy instructions or script, so far all i can do is pnpm build, which runs fine
- a way to get nvim-vtsls to pick up vtsls from /usr/local/bin... i didnt explore this very fully though

**Comment by unphased** [comment]
I'm sorry but could i ask you to run a release? I don't know how much longer it would take for me to figure out your release process. It's probably simple but I don't like reverse engineering.

**Comment by yioneko** [comment]
From what I can tell, `mason.nvim` doesn't provide capability to customize the installation process. So 
> how to tell mason to grab main instead of specific commit.

might be impossible.

If you have built it successfully, just change the cmd of vtsls config of lspconfig should be enough:

```lua
require('lspconfig').vtsls.setup({ cmd = {"node", "path_to_vtsls_pacakges_server_bin_vtsls.js", "--stdio"} })
```

I'm sorry that the installation instruction is over-simplified; I'll improve it. New release will be soon available for easy testing.

**Comment by unphased** [comment]
No worries. I still figure my path of least resistance is to surgically update the mason installation *somehow* as that is apparently the only way i can get vtsls show up in nvim as an enabled LSP. So i will poke around these parts.

**Comment by unphased** [comment]
I saw 0.1.24 was released inside mason so i have updated it. 

I can see within mason's install dir inside vtsls: `~/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/@vtsls/language-service/package.json` says: 

```
{
  "name": "@vtsls/language-service",
  "description": "LSP wrapper for typescript extension of vscode",
  "version": "0.1.24",
...
```
Which is encouraging, however I still dont see the move to file action and also i see inside dist/index.js and dist/index.mjs: 

```
  get unsupported_actions() {
    return this.configuration.getConfiguration("vtsls").get("enableMoveToFileCodeAction") ? [] : ["refactor.move.file"];
  }
```
I note this is a different form than the above `var UNSUPPORTED_ACTIONS = ["refactor.move.file"];` that I saw from 0.1.23.

**Comment by unphased** [comment]
Can you tell me if `require('lspconfig').vtsls.setup` is the same at all with `require('vtsls').config`? The former fails with `E5113: Error while calling lua chunk: /home/slu/.vim/nvim/init.lua:1740: attempt to call field 'setup' (a nil value)`

**Comment by unphased** [comment]
After logging out the structures i can see i'm trying this 

```lua
local vtsls = require("vtsls")
local vt_lspc = vtsls.lspconfig;
vt_lspc.default_config.cmd = { "node", vim.fn.expand("$HOME") .. '/vtsls/packages/server/bin/vtsls.js', '--stdio' }
require('lspconfig.configs').vtsls = vt_lspc;
```
but no dice, it doesnt pick up the config. I'm following the readme instructions for config but they don't seem to do anything.

**Comment by yioneko** [comment]
> Can you tell me if require('lspconfig').vtsls.setup is the same at all with require('vtsls').config

The former one is from `nvim-lspconfig` and is required to setup the server. The latter is totally optional if you don't need to change the defaults of this plugin (the plugin automatically activate itself when vtsls attached to a buffer).

It is weird that `require('lspconfig').vtsls` is reported to be nil. [It is included in lspconfig builtins](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#vtsls).

**Comment by unphased** [comment]
Ah! I achieved it. With this config. It is surely bad or wrong but it's enough to make me see the new code action. 

```lua
local vtsls = require("vtsls")
local vt_lspc = vtsls.lspconfig;
vt_lspc.default_config.cmd = { "node", vim.fn.expand("$HOME") .. '/vtsls/packages/server/bin/vtsls.js', '--stdio' }
log('xxx', vt_lspc)
require('lspconfig.configs').vtsls = vt_lspc
vtsls.config({})
require("lspconfig").vtsls.setup({})
```

pointed against vtsls built locally. we should still figure out why 0.1.24 doesnt show the new code action.

**Comment by unphased** [comment]
For some reason that config worked for a few minutes and then it started doing `E5113: Error while calling lua chunk: /home/slu/.vim/nvim/init.lua:1740: attempt to call field 'setup' (a nil value)` again.

**Comment by yioneko** [comment]
Could you try just:
```lua
require("lspconfig").vtsls.setup({
  cmd = { "node", vim.fn.expand("$HOME") .. '/vtsls/packages/server/bin/vtsls.js', '--stdio' },
  settings = {
     vtsls = {
	enableMoveToFileCodeAction = true,
    },
})
```
No need to call `require('vtsls')`.

**Comment by unphased** [comment]
That looks like is all I need and working for me. thank you.

**Comment by unphased** [comment]
I can confirm btw it does work as intended. the file picker behaves a bit strange (just a normal mode popup it seems) but i have no problem with that right now.

**Comment by yioneko** [comment]
Thanks for your patience. The file picker is triggered by `vim.ui.select`. You can read the help doc of it for its customization, which is out of the scope of this plugin. There is also [dressing.nvim](https://github.com/stevearc/dressing.nvim) implementing a telescope picker for `vim.ui.select`, which I guess is what you expect.

**Comment by unphased** [comment]
I do have dressing installed and will let you know if i have further problems with it. I can also confirm now testing on my mac that with the latest config you gave me, i have:

- commented out the cmd override
- installed 0.1.24 via mason

the new code action is showing up! 

```
  settings = {
     vtsls = {
	enableMoveToFileCodeAction = true,
    }
  }
```
seems important.

**Pull request merged**
